### ISSUE TITLE
$20 & $21 settings getting set to zero

### ISSUE THREAD

**Issue by Neex101** [YetiTool/easycut-smartbench#108]
Think this is due to failure to complete initial homing op (with squaring function)

**Comment by LettyYeti** [comment]
I assume setting limits back to 1 only works when the machine knows where it is again?

**Comment by LettyYeti** [comment]
@Neex101 have you fixed this in the new homing stuufff?

**Comment by Neex101** [comment]
Yes this now fixed up good and proper
