### ISSUE TITLE
Major sleep lag if console left unattended for a while

### ISSUE THREAD

**Issue by Neex101** [YetiTool/easycut-smartbench#113]
Can take a long time to wake up.
Seems the longer it is left, the longer it takes. Can take up to half a minute. 
User thinks console has crashed and hard resets

**Comment by Neex101** [comment]
Is this due to excessive logging?

**Comment by LettyYeti** [comment]
Think this could be majorly attentuated by adding/removing widgets and screens on the go, as opposed to having everything loaded all the time.

**Comment by LettyYeti** [comment]
SORTED 0.3.3
