### ISSUE TITLE
If axis limit switch is already triggered, can't home

### ISSUE THREAD

**Issue by Neex101** [YetiTool/easycut-smartbench#114]
Just get an alarm saying that the limit switch is triggered.

**Comment by Neex101** [comment]
Updating info to advise power down, move head and repower.
Future fix may be to disable hard limits, move, re-enable limits.

**Comment by LettyYeti** [comment]
Don't need to do that! Just need to check if system is in alarm state before homing! If reset machine can home again :)

**Comment by Neex101** [comment]
Really? Mine doesn't. Just alarms again.
