### ISSUE TITLE
Rebooting screen needed

### ISSUE THREAD

**Issue by Neex101** [YetiTool/easycut-smartbench#122]
A ticket was raised because customer assumed console crashed after entering wifi details (when actually it was rebooting as intended).
We need a 2 second screen to say EC's going to reboot.
A reboot screen could be called, and the screen's `on_enter` function could schedule the reboot function which would be nice and contained.

**Comment by LettyYeti** [comment]
Merged into master-dev branch, should all be fine, but also got rid of some obselete files and things at the same time so good to test all first ;)

**Comment by Klazomenai** [comment]
Looks to be resolved via the main [dev merge](https://github.com/YetiTool/easycut-smartbench/pull/159) in.
