### ISSUE TITLE
Add "on limit switch" detection to enable homing function 

### ISSUE THREAD

**Issue by Neex101** [YetiTool/easycut-smartbench#125]
Sometimes an axis can already be on a limit switch when the machine is asked to home.
This causes an alarm.
So the machine cannot home. So the alarm persists. So the machine cannot home etc etc etc.
Proposed solutions:
On entering homing function:
Pre-check grbl status to examine if any limits are arleady  triggered (shown in the `Pn:` section of the status). If found, move 20 mm in the direction that would untrigger the switch. THEN continue with homing function.
Pn: x = min x limit switch triggered
Pn: X = max x limit switch triggered
Pn: y = min y limit switch triggered
Pn: Y = max Y limit switch triggered
Pn: z = min z limit switch triggered

**Comment by LettyYeti** [comment]
I'm not seeing this error on the test rig either? I can have the axes right up on the limit switches and homing still runs fine, no alarms seen?

**Comment by Neex101** [comment]
We need to sync your version of grbl

**Comment by LettyYeti** [comment]
@Neex101 can we close this?

**Comment by Neex101** [comment]
Brings back some horrible memories :-) Ditch!

**Comment by Neex101** [comment]
(no, done!)
