### ISSUE TITLE
Optimise logging

### ISSUE THREAD

**Issue by Neex101** [YetiTool/easycut-smartbench#126]
From @Klazomenai :
We should have two modes of logging. Error/warning only for the wild and debug for the dev benches. Debugging mode should also be able to be turned on or off from the console. That will behave nicely, the only problem being that you won't have debug messages for the wild for if a specific cut will break. Debug mode will need to be turned on an another equal cut run to get the debug messages. But generally, debug logging is avoided in production.

**Comment by Neex101** [comment]
Specific reference to the grbl status logs which are currently @ 10Hz

**Comment by Neex101** [comment]
Possible cause of slowdown

**Comment by LettyYeti** [comment]
send Ed sample logs

**Comment by Neex101** [comment]
Cleaned up

**Comment by Neex101** [comment]
Ah, wrong thread

**Comment by LettyYeti** [comment]
@Neex101 can I assume this is covered by Job Logging in trello?

**Comment by Neex101** [comment]
Yep
