### ISSUE TITLE
Bigger text on filechooser filenames

### ISSUE THREAD

**Issue by Neex101** [YetiTool/easycut-smartbench#137]
Larger font (50 percent increase)
Double spaced (don't know how in that one) for fat fingers
Reduce width on image placeholder to allow for as much text width as possible - some files are only uniquely identified by last few chars in file name, which can be quite long

**Comment by Neex101** [comment]
Absolutely no idea how to implement the `style.kv` file to change filchooser template. Reassigning!

**Comment by LettyYeti** [comment]
duplicate issue
