### ISSUE TITLE
Finished file screen displays before the job has physically finished. The screen displays upon the buffer emptying and needs a delay

### ISSUE THREAD

**Issue by LettyYeti** [YetiTool/easycut-smartbench#144]
Have asked Mac for enlightenment on how long delay should be.

**Comment by LettyYeti** [comment]
- Overcome by checking IDLE status

**Comment by Neex101** [comment]
Can I suggest a cleaner way?
Append a grbl delay command (of 0.1 seconds) to the end of the GCode stream. Since grbl won't release the ok until the delay is complete, the final ok won't appear until the true end of the file completion.

**Comment by LettyYeti** [comment]
@Neex101 fairly sure you fixed this - can you confirm/close plz X

**Comment by Neex101** [comment]
Yep, fixed
