### ISSUE TITLE
Is buffer stuffing a significant time saver when checking a file?

### ISSUE THREAD

**Issue by Neex101** [YetiTool/easycut-smartbench#145]
Context, a 5Mb file currently takes over 4 hours.

OPTION 1

On the file checking - when we check with grbl, we sequentially stream. This is makes it easy to match errors with lines of code, but the flip side is that it is slow. A quicker way is to buffer-stuff (which is what we do for a real job), but requires more code to reconcile errors.

From Pi to grbl with sequential streaming, Mac's 6mB file was never completed because it was taking in excess of 4 hours (btw we should run this again on monitor to ensure that the job was actually getting checked, rather than it had just stopped for some reason). From my Surface to grbl using the buffer stuffing technique (via EC), it took 9 minutes. Granted my Surface has way more grunt, but this tells me we should run a bs test on the Pi to evaluate the impact of buffer stuffing during checking,

I seem to remember the initial grbl example script for keeping track of lines sent and resposes recv'd quite neat: 
https://github.com/gnea/grbl/blob/master/doc/script/stream.py

**Comment by LettyYeti** [comment]
Fixed v0.3.2
 0b2113b
