### ISSUE TITLE
Long delay entering control screen if large file loaded

### ISSUE THREAD

**Issue by Neex101** [YetiTool/easycut-smartbench#155]

**Comment by LettyYeti** [comment]
@Neex101 can you confirm that the lag keeps you in the file loading screen rather than the home screen? Thx

**Comment by Neex101** [comment]
Can't remember where the lag was (gun to head I'd say it was after the entering the home screen, but it's been a while since we've run a large file). Suggest trying a large (~2Mb) file and see what happens.

**Comment by LettyYeti** [comment]
aha. I see. Yes, that is annoying.

**Comment by LettyYeti** [comment]
Fixed v0.3.2
 0b2113b
