### ISSUE TITLE
User entry field for probe plate thickness

### ISSUE THREAD

**Issue by Neex101** [YetiTool/easycut-smartbench#169]
User receives new probe plate, or machine is being setup for the first time. 
Operator needs to enter thickness into EC, so EC can correctly calculate z0 height during probing.

**Comment by LettyYeti** [comment]
@Neex101 still relevant? 

If yes, should it be moved into maintenance or calibration?

**Comment by Neex101** [comment]
Yes to both

**Comment by Neex101** [comment]
Move to maintenance

**Comment by LettyYeti** [comment]
migrated to trello
