### ISSUE TITLE
WiFi country code input handling

### ISSUE THREAD

**Issue by Neex101** [YetiTool/easycut-smartbench#21]
This field is another point of failure if wrong country code is entered.

I suspect intent is only about signal attenuation to meet different geographical  compliances.

Suggest drop down of options, though if I'm right on its intent, listing compliance zones (e.g. Europe (CE), USA (FCC), ...) rather than the whole list of countries in the world! Needs a bit of testing obvs.

**Comment by LettyYeti** [comment]
hide this and then have a difficult way to change if required
