### ISSUE TITLE
USB "repair drive" bug

### ISSUE THREAD

**Issue by LettyYeti** [YetiTool/easycut-smartbench#211]
From customer - Whenever I reattached my USB drive to my computer AFTER having it attached to the SmartBench, I encounter a "repair drive" prompt from my computer. I would run the repair drive prompt, try again, but keep receiving the same message, only after attaching the USB to the SmartBench. 

https://yetitool.atlassian.net/browse/CI-3

**Comment by LettyYeti** [comment]
@AzYeti @Neex101 I expect this to be solved by the changes to USB reliability, but obvs needs confirmation.

**Comment by Neex101** [comment]
Cheers will test... @AzYeti you got any repeatable fail procedures from before which I can test?

**Comment by Neex101** [comment]
@AzYeti you still seeing issues since latest master?

**Comment by AzYeti** [comment]
Haven’t tested enough yet. Need to get a customer onto master to test but their closed

 

Thanks,

Aaron

**Comment by AzYeti** [comment]
Yes,  I had a customer with this issue yesterday
