### ISSUE TITLE
Retract spindle when job is paused

### ISSUE THREAD

**Issue by LettyYeti** [YetiTool/easycut-smartbench#213]
When the job is paused either using the console or stop bars, can the spindle retract out of the material to allow the front of the dust shoe to be removed and the dust shoe be cleaned out?

https://yetitool.atlassian.net/browse/EC-85

**Comment by LettyYeti** [comment]
Would be GREAT if could pause, it raises the spindle, and allows user to move the spindle using the directional arrows, then when the user hits RESUME, it goes back to the paused location, turns on spindle and drops to proper Zheight.

Allows user to clear extraction blockages

**Comment by Neex101** [comment]
Still needs doing, but tool chain is too long to be able to fit this into v1.1 m'afraid.
