### ISSUE TITLE
tap on the ./ line in usbstick load file crash everything. need reboot

### ISSUE THREAD

**Issue by sergevi** [YetiTool/easycut-smartbench#223]
I often tap a little too high on the file manager in the USB file chooser and choose the "./" line.
I immediately get the yetitool spashscreen and impossible to come back.
Need to stop and restart all.

**Comment by Neex101** [comment]
@sergevi thanks for logging this, we're scheduling a fix for our next milestone release.
Annoyingly this is a funciton which is quite deep in the kivy framework, but we'll have a go!

**Comment by sergevi** [comment]
you welcome. It doesn't prevent to work at all  :) I pay attention now and all is good.. happy you will debug it :)

**Comment by Neex101** [comment]
We'll get there!

**Comment by Neex101** [comment]
@Lettie, from memory, I think switching to `iconView` as the filechooser template might actually get rid of this problem - weird, I know, but lets try

**Comment by Neex101** [comment]
@AzYeti pls confirm this is now fixed

**Comment by Neex101** [comment]
Thanks @sergevi this is now fixed and ready for next release (due next week :-)
