### ISSUE TITLE
File explorer change

### ISSUE THREAD

**Issue by LettyYeti** [YetiTool/easycut-smartbench#246]
Change file explorer list to tiles - something more robust for big fingers!
To solve the problem of only 8 chars being displayed on the filename under the icon, lets put a label at the bottom of the filechooser which displays the full name, so the user can confirm exactly which file it is before they cvommit to the job.

**Comment by Neex101** [comment]
@LettyYeti check my update to this description - I propose a cheap hack which will address the issue well, and shouldn't make this a project :-)

**Comment by Neex101** [comment]
Also from memory it solve the problem in #223
