### ISSUE TITLE
Cancel homing when in alarm state = bluescreen crash

### ISSUE THREAD

**Issue by Neex101** [YetiTool/easycut-smartbench#287]
v0.4.0
Steps to repeat:
Turn on.
Cause alarm (e.g. press Y limit switch).
Home... get dialogue of "it's in alarm, do you wanna clear and home".
Press no (/cancel)
Crashes

![image](https://user-images.githubusercontent.com/29443660/77106218-a64b5100-6a16-11ea-841a-016cf2fbe442.png)

**Comment by LettyYeti** [comment]
@Neex101 is this on your riggy? I have never seen this problem...

**Comment by LettyYeti** [comment]
Retract that statement. Just tested. Wtf.

**Comment by Neex101** [comment]
Log updated into description
