### ISSUE TITLE
Set wifi credentials form UI

### ISSUE THREAD

**Issue by Neex101** [YetiTool/easycut-smartbench#3]
Currently UI hooks are in, but python code is old/irrelevant/non-functional:

https://github.com/YetiTool/easycut-smartbench/blob/master/src/asmcnc/skavaUI/widget_network_setup.py

**Comment by LettyYeti** [comment]
This is what we fixed right? Can I close this @Neex101 ?

**Comment by Neex101** [comment]
Yep
