### ISSUE TITLE
"Set datum?" confirmation screen

### ISSUE THREAD

**Issue by Neex101** [YetiTool/easycut-smartbench#30]
Currently it is too easy to hit set instead of go and that is a pain to deal with.

**Comment by LettyYeti** [comment]
![image](https://user-images.githubusercontent.com/47244859/53486137-d3ca0300-3a7f-11e9-88bf-2a977d7d0cf5.png)

**Comment by LettyYeti** [comment]
![image](https://user-images.githubusercontent.com/47244859/53486208-096eec00-3a80-11e9-92d4-7e892e6aa547.png)

**Comment by Neex101** [comment]
Just a popup right?
