### ISSUE TITLE
USB reliability

### ISSUE THREAD

**Issue by Neex101** [YetiTool/easycut-smartbench#336]
Az is getting some reports of USB drive not working.
Some of this will be down to dodgy sticks. But since I wrote the module on USB detection, there could also be conditions in which the detection breaks.

**Comment by LettyYeti** [comment]
Functions have been put into USB module to mount and unmount the USB drive, but USB is actually only ever unmounted if directory "is empty" - i.e. never an option to safely let you remove your hardware!

**Comment by Neex101** [comment]
Aha!

**Comment by LettyYeti** [comment]
Separate issue for the new USB notification pop-ups
