### ISSUE TITLE
Developer app

### ISSUE THREAD

**Issue by Neex101** [YetiTool/easycut-smartbench#349]
Lobby level access to dev screen
Needs a pop-up `on_enter` to warn user pressing buttons may damage their machine
Ed to spec wireframe

**Comment by Neex101** [comment]
Functional spec handed to @AzYeti for wireframing

**Comment by AzYeti** [comment]
Wire Frame completed - implement for V1.3?

**Comment by LettyYeti** [comment]
migrated to trello, UX project
