### ISSUE TITLE
Dedicated module for job

### ISSUE THREAD

**Issue by Neex101** [YetiTool/easycut-smartbench#387]
Strikes me that a "job" should have its own class. Rather than be sagged out over many other classes.
Be much clearer to see its centralised operating functions, and I suspect we may come across some redundant/inefficient calls along the way.

Suggest created a child of `machine` (sibling of `serial`), since machine should only ever have one job

**Comment by LettyYeti** [comment]
part of refactoring

**Comment by LettyYeti** [comment]
migrated to trello
