### ISSUE TITLE
Dev G-Code switch doesn't seem to do anything

### ISSUE THREAD

**Issue by LettyYeti** [YetiTool/easycut-smartbench#41]

**Comment by Neex101** [comment]
What is Dev G-Code switch?

**Comment by LettyYeti** [comment]
Under the dev tab, there is a switch to turn on/off GRBL gcode check. It does not seem to do anything other than toggle.

**Comment by Neex101** [comment]
This button can now be dropped

**Comment by LettyYeti** [comment]
button dropped
