### ISSUE TITLE
Homing error on "Home" button press during testing with arduino

### ISSUE THREAD

**Issue by LettyYeti** [YetiTool/easycut-smartbench#46]
Pressing home button, even at start up, on both master and LoadingScreen branches results in following error screen popping up:    

"error:5"  : "Homing cycle is not enabled via settings.",

**Comment by Neex101** [comment]
This is a dollar setting in grbl, just needs to be put to a "1" value

**Comment by LettyYeti** [comment]
Is this an exlclusively arduino problem?
