### ISSUE TITLE
Raise the Spindle

### ISSUE THREAD

**Issue by LettyYeti** [YetiTool/easycut-smartbench#54]
If spindle is lowered and you want to move to the job's location, SB will not raise the spindle and in some cases it can cause cutter to catch on material.

![image](https://user-images.githubusercontent.com/47244859/54324086-0df4e200-45f4-11e9-97b5-d9cdcc70c6de.png)

![image](https://user-images.githubusercontent.com/47244859/54324107-2107b200-45f4-11e9-96e2-3c186a7d1ac5.png)

**Comment by LettyYeti** [comment]
@Neex101 

For solution to this: is it ok to just add m.zUP as the first command for these buttons?

**Comment by Neex101** [comment]
Yep.
I worry that this safety net will annoy pro users. But we'll cross that bridge when we come to it. I'm thinking we'd demand a second button to be pushed simulataneously (like using the shift key) to allow an XY move without a zUp.
