### ISSUE TITLE
Disable double tap for move button commands

### ISSUE THREAD

**Issue by Neex101** [YetiTool/easycut-smartbench#60]
Currently double tap yields full down press results

**Comment by LettyYeti** [comment]
@Neex101 more info needed on this one please

**Comment by Neex101** [comment]
On manual move screen, up/down/left/right buttons... double tapping the button locks the button down, yielding an unexpectedly long move. Danger danger.

**Comment by LettyYeti** [comment]
Kivy config file settings

**Comment by LettyYeti** [comment]
Needs to be fixed within GRBL settings:

" a GRBL cancel Jog command (x85) will only work if it's not already cancelling a jog. So if you send the following in quick succession "Jog, Cancel, Jog, Cancel", the second cancel won't register whilst the first jog is in progress. It seems, however, the the second Jog is maybe added after the first cancel has flushed the buffer, so then the second Jog still happens..."

**Comment by LettyYeti** [comment]
@Neex101 did the FW update help with this at all? Can't remember

**Comment by Neex101** [comment]
Nope, double tap is alive and well, even on latest f/w :-(
