### ISSUE TITLE
Jog speed doesn't reset between jobs

### ISSUE THREAD

**Issue by Neex101** [YetiTool/easycut-smartbench#61]
So logic is broken on second job

**Comment by LettyYeti** [comment]
More info please @Neex101

**Comment by Neex101** [comment]
During job, XYZ feed speeds can be adjusted using the dial on the bottom left of go screen. Makes machine go faster or slower, on the fly. Very useful.

On starting a new job, grbl resets speed adjustment back to 100%. But EC doesn't reset it's feed adjustment logic back to 100%. So EC gets out of sync after the first job.

Simple fix, EC parameters just need resetting to 100% on every job start.
