### ISSUE TITLE
zUp at start of job - better polling

### ISSUE THREAD

**Issue by Neex101** [YetiTool/easycut-smartbench#70]
https://github.com/YetiTool/easycut-smartbench/blob/master/src/asmcnc/comms/serial_connection.py#L312

Needs treatment with Clock
scheduling and/or additional use of "G4 P1" which release a second 'ok'
to be counted.

**Comment by LettyYeti** [comment]
While loop destroyed. 

Think problem was actually being caused by dodgy indexing in process_grbl_response.
