### ISSUE TITLE
Safety warning

### ISSUE THREAD

**Issue by Neex101** [YetiTool/easycut-smartbench#86]
Before allowing user into app, we need to display safety reminders on a "click to agree" screen.
Do's and don'ts
Az is doing the manual and has come across a lot of items.
For now, lets get some cover-all bullet points in (e.g. use PPE, don't stick hands into moving machinery, slippery when wet etc)

**Comment by LettyYeti** [comment]
@Neex101 you want any more on this screen?

**Comment by Neex101** [comment]
All good now
