### ISSUE TITLE
Deactivate/clear redundant buttons

### ISSUE THREAD

**Issue by Neex101** [YetiTool/easycut-smartbench#89]
E.g. need a coming soon for the two other apps seen in the lobby & deactivate scond one (it's live to a shape generating screen which skippy didn't finish)
Dev area needs sectioning off
There's a "template" button on the job screen (page symbol with a star on it) which leads to some unfinished tempalte dialogue
... and probz more items

**Comment by LettyYeti** [comment]
Have sorted the template and lobby buttons. 

Dev area has a separate Git issue so will section that off. 

Have added question label bc need to know whether there is other stuff that needs addressing.

**Comment by LettyYeti** [comment]
VIEW BUTTONS ON VIRTUAL BED

**Comment by LettyYeti** [comment]
@Neex101 what are the view buttons meant to do - should I add a new ticket to add in functionality for them or just ditch them completely for now?

**Comment by Neex101** [comment]
Ditch
